// Mock data cho Fit AI Challenge App

export const mockWorkouts = [
  {
    id: 1,
    title: '30-Day Plank Challenge',
    description: 'Build core strength with progressive plank exercises',
    difficulty: 'Intermediate',
    duration: '30 days',
    participants: 1234,
    image: 'https://images.unsplash.com/photo-1756115484694-009466dbaa67?w=400',
    category: 'Core',
  },
  {
    id: 2,
    title: 'AI Running Challenge',
    description: 'AI-powered running plan to improve your speed',
    difficulty: 'Advanced',
    duration: '8 weeks',
    participants: 856,
    image: 'https://images.unsplash.com/photo-1759476530203-b11476530203?w=400',
    category: 'Cardio',
  },
  {
    id: 3,
    title: 'Yoga Flow Mastery',
    description: 'Master yoga sequences with AI guidance',
    difficulty: 'Beginner',
    duration: '21 days',
    participants: 2145,
    image: 'https://images.unsplash.com/photo-1723406251893-88cfd80c566b?w=400',
    category: 'Flexibility',
  },
];

export const mockChallenges = [
  {
    id: 1,
    title: '100 Push-ups Challenge',
    description: 'Complete 100 push-ups daily for 30 days with AI form tracking',
    reward: '500 AI Points + Badge',
    difficulty: 'Hard',
    startDate: '2025-11-01',
    endDate: '2025-11-30',
    participants: 3421,
    aiScore: 95,
    image: 'https://images.unsplash.com/photo-1760115965215-27ad35ffc24e?w=400',
    status: 'Active',
  },
  {
    id: 2,
    title: 'Mindful Movement Week',
    description: 'Daily yoga and meditation tracked by AI wellness coach',
    reward: '300 AI Points',
    difficulty: 'Easy',
    startDate: '2025-10-25',
    endDate: '2025-10-31',
    participants: 1892,
    aiScore: 88,
    image: 'https://images.unsplash.com/photo-1723406251893-88cfd80c566b?w=400',
    status: 'Active',
  },
  {
    id: 3,
    title: 'Sprint Master 5K',
    description: 'AI-coached 5K running program with speed analysis',
    reward: '750 AI Points + Trophy',
    difficulty: 'Medium',
    startDate: '2025-11-05',
    endDate: '2025-12-05',
    participants: 2764,
    aiScore: 92,
    image: 'https://images.unsplash.com/photo-1759476530203-b11cc8c87d43?w=400',
    status: 'Upcoming',
  },
];

export const mockLeaderboard = [
  {
    rank: 1,
    userId: 'u1',
    username: 'FitWarrior2024',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FitWarrior',
    aiScore: 9850,
    challengesCompleted: 24,
    streak: 45,
  },
  {
    rank: 2,
    userId: 'u2',
    username: 'YogaMaster_AI',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YogaMaster',
    aiScore: 9620,
    challengesCompleted: 21,
    streak: 38,
  },
  {
    rank: 3,
    userId: 'u3',
    username: 'CardioKing',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CardioKing',
    aiScore: 9310,
    challengesCompleted: 19,
    streak: 32,
  },
  {
    rank: 4,
    userId: 'u4',
    username: 'StrengthQueen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=StrengthQueen',
    aiScore: 8975,
    challengesCompleted: 18,
    streak: 29,
  },
  {
    rank: 5,
    userId: 'u5',
    username: 'FlexibilityPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FlexPro',
    aiScore: 8654,
    challengesCompleted: 17,
    streak: 25,
  },
];

export const mockCommunityPosts = [
  {
    id: 1,
    userId: 'u1',
    username: 'FitWarrior2024',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FitWarrior',
    content: 'Just completed my 100th push-up! AI Coach feedback is amazing! 💪',
    image: 'https://images.unsplash.com/photo-1756115484694-009466dbaa67?w=600',
    likes: 124,
    comments: 18,
    timestamp: '2 hours ago',
  },
  {
    id: 2,
    userId: 'u2',
    username: 'YogaMaster_AI',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YogaMaster',
    content: 'Morning yoga session with AI posture tracking. Feeling energized! 🧘‍♀️',
    image: 'https://images.unsplash.com/photo-1723406251893-88cfd80c566b?w=600',
    likes: 89,
    comments: 12,
    timestamp: '5 hours ago',
  },
  {
    id: 3,
    userId: 'u3',
    username: 'CardioKing',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CardioKing',
    content: 'New PR! 5K in 22 minutes thanks to AI pacing coach 🏃‍♂️🔥',
    likes: 156,
    comments: 23,
    timestamp: '1 day ago',
  },
];

export const mockUserProfile = {
  id: 'current-user',
  username: 'MyFitJourney',
  email: 'myfit@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MyFit',
  joinDate: '2025-01-15',
  aiScore: 5420,
  challengesCompleted: 12,
  currentStreak: 15,
  totalWorkouts: 78,
  goals: {
    weeklyWorkouts: 5,
    dailyCalories: 500,
    monthlyDistance: 50,
  },
  stats: {
    totalCaloriesBurned: 12450,
    totalMinutes: 2340,
    favoriteWorkout: 'Yoga',
  },
};

export const mockDashboardStats = {
  weeklyCalories: 2340,
  weeklyWorkouts: 6,
  weeklyMinutes: 420,
  currentStreak: 15,
  todayProgress: {
    calories: 420,
    caloriesGoal: 500,
    workouts: 2,
    workoutsGoal: 2,
    minutes: 65,
    minutesGoal: 60,
  },
  weeklyChart: [
    { day: 'Mon', calories: 380, minutes: 55 },
    { day: 'Tue', calories: 420, minutes: 70 },
    { day: 'Wed', calories: 350, minutes: 50 },
    { day: 'Thu', calories: 400, minutes: 65 },
    { day: 'Fri', calories: 390, minutes: 60 },
    { day: 'Sat', calories: 0, minutes: 0 },
    { day: 'Sun', calories: 400, minutes: 60 },
  ],
};
