name: Deploy to S3

on:
  push:
    branches:
      - main  # Tự động deploy khi push lên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: ./FIT_AI_Challenge_WEP/APP_FE
        run: npm install
      
      - name: Build
        working-directory: ./FIT_AI_Challenge_WEP/APP_FE
        run: npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Deploy to S3
        working-directory: ./FIT_AI_Challenge_WEP/APP_FE
        run: aws s3 sync dist/ s3://fit-ai-challenge-frontend --delete
